[project]
name = "scraping-selenium-mongodb"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "selenium>=4.39.0",
    "webdriver-manager>=4.0.2",
]
